### ISSUE TITLE
Bug: Database is locked on article create

### ISSUE THREAD

**Issue by olehcambel** [xesina/golang-echo-realworld-example-app#12]
Steps to reproduce:
1. create article (POST `/article`) with title = "string"
2. try the same request . You will get an error
    ```json
    {
        "errors": {
            "body": "UNIQUE constraint failed: articles.slug"
        }
    }
    ```
3. As transaction has started and not rollback or commit, when you run the same request, you will get
    ```json
    {
        "errors": {
            "body": "database is locked"
        }
    }
    ```

Solution is to add `tx.Rollback()` before returning error in create
https://github.com/xesina/golang-echo-realworld-example-app/blob/master/store/article.go#L44-L47
https://github.com/xesina/golang-echo-realworld-example-app/blob/master/store/article.go#L71

**Comment by xesina** [comment]
Thanks @olehcambel, fixed :)

**Comment by olehcambel** [comment]
Great!
